#외부동기화
services:
  myapp:
    build:
      context: .              # Dockerfile이 있는 디렉토리
      dockerfile: Dockerfile  # Dockerfile 이름 (기본값)
    volumes:
      - myapp-sync:/app        # docker-sync에서 생성한 볼륨
    # ports:
    #   - "3000:3000"            # 필요한 포트 매핑 (예시)
    #command: valgrind --leak-check=full --track-origins=yes ./minishell
    stdin_open: true
    tty: true

volumes:
  myapp-sync:
    external: true              # 외부 볼륨으로 설정


# #직접동기화
# version: '3'
# services:
#   myapp:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app  # 호스트 디렉토리와 컨테이너의 /app 디렉토리 간의 직접 동기화
#     command: valgrind --leak-check=full --track-origins=yes ./my_program
#     stdin_open: true
#     tty: true
